@startuml

title TogglIQ UI Control

class TimerView
class WarningView

class NotificationView

interface IView {
  + void update(dc)
}

class MainView {
}

class AboutView

class ViewController {
}

class TimerModel {
}

class WarningModel {
}

class NotificationModel {
}

enum ViewKey {
    Main,
    About
}

MainView *-- IView

IView <|-- TimerView
IView <|-- WarningView
IView <|-- NotificationView

TimerView *-- TimerModel
WarningView *-- WarningModel
NotificationView *-- NotificationModel

@enduml
